### PR TITLE
Move to esm

### PR DESCRIPTION
**Pull request by jairhenrique**
@webpro I don't know why it's failing the tests.

```
⟩ npm test

> @release-it/bumper@3.0.1 test
> bron test.js

✔ should not write in dry run
✔ should not throw
✔ should write new, indented JSON file
✔ should write version at path
✔ should write version at multiple paths
✔ should write plain version text file
✔ should write plain version text file (default text type)
fish: Job 1, 'npm test' terminated by signal SIGABRT (Abort)
```

### CODE REVIEW

**Review by matheusrufinos — APPROVED** [review]
🙏

**Comment by jairhenrique** [comment]
Fixed all erros!
Screen Shot 2021-12-20 at 14 45 45

**Comment by jairhenrique** [comment]
@webpro can you review this!?

**Comment by webpro** [comment]
Thanks @jairhenrique! The updates looks great, just two things:

- I've added the Prettier config in the `master` branch, could you please apply the same styling again?
- I've added the `feature/es-modules` branch in my repo. Can you point this PR to that branch? Then I can make pre-releases from there first.

Thanks again for all the work :)

**Comment by jairhenrique** [comment]
@webpro done!

**Pull request merged**
